config/routes.rb
Rails.application.routes.draw do

  get "users/show"

  resources :pins

  devise_for :users
  

  root :to => "pins#new"
  get "discover" => "pins#discover"
  get "discoverkicked" => "pins#discoverkicked"
  get "mylist" => "pins#mylist"
  get "myprofile" => "pins#myprofile"
  get "about" => "pages#about"
  get "howitworks" => "pages#howitworks"
  resources :users
  get "ultimate_user_list" => "users#ultimate_user_list"

end

app/models/pin.rb
class Pin < ActiveRecord::Base
		belongs_to :user

		has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
		validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]

		validates :description, presence: true
		validates :description, length: {maximum: 75 }
		validates :description, length: {minimum: 2 }
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins, dependent: :destroy 
  has_attached_file :image, :styles => { :medium => "100x100>", :thumb => "50x50>" }, :default_url => "/images/:style/missing.png"

  validates :name, presence: true
  validates :name, length: {maximum: 15 }
  validates :name, length: {minimum: 2 }
  validates :name, uniqueness: true 
  validates :image, presence: true 
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

def show
  @user = User.find(params[:id])
end

protected

 def configure_permitted_parameters
   devise_parameter_sanitizer.for(:sign_up) << :name
   devise_parameter_sanitizer.for(:account_update) << :name
   devise_parameter_sanitizer.for(:sign_up) << :image
   devise_parameter_sanitizer.for(:account_update) << :image
 end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
  def mylist
  end
  def howitworks
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page =>150)
  end

  def mylist
    @pins = current_user.pins.all.order("created_at DESC").paginate(:page => params[:page], :per_page =>150)
  end

  def myprofile
    @pins = current_user.pins
  end

  def discover
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page =>150)
  end

  def discoverkicked
    @pins = Pin.all.order("created_at DESC").paginate(:page => params[:page], :per_page =>150)
  end
  
  # GET /pins/1
  # GET /pins/1.json
  def show
    @pins = Pin.all.order("created_at DESC").where("description LIKE ?", "#{@pin.description}%")
  end

  # GET /pins/new
  def new
    @pin = current_user.pins.build
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = current_user.pins.build(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Successfully created!' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to current_user, notice: 'Successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    def correct_user
        @pin = current_user.pins.find_by(id: params[:id])
        redirect_to pins_path, notice: "Not authorized to edit this post" if @pin.nil?
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:description, :image)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def show
  @user = User.find(params[:id])
	end

	def ultimate_user_list
	@user = User.order("created_at DESC")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> 
        <% if user_signed_in? %>
        <%= link_to "KickTheList", current_user, class: "navbar-brand" %> <!--image_tag("https://s3.amazonaws.com/kickthelist/media/logo/KickTheListLogo.png", :size => "25x25") -->
        <% else %> 
        <%= link_to "KickTheList", root_path, :"data-no-turbolink" => true, class: "navbar-brand" %>
        <% end %>

    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse navbar-ex1-collapse">
      <ul class="nav navbar-nav navbar-right">
        <!-- <li><%= link_to "Home", root_path,  :"data-no-turbolink" => true unless user_signed_in? %></li> -->
        <!-- <li><%= link_to "About", about_path unless user_signed_in? %></li> -->
        <!-- <li><%= link_to "Sign Up", new_user_registration_path unless user_signed_in? %></li> -->
            <% if user_signed_in? %>
              <li><%= link_to "+", new_pin_path %>
              <li><%= link_to "My List", current_user, :"data-no-turbolink" => true %></li>
              <!-- <li><%= link_to "Discover", discover_path %></li> -->
              <!-- <li><%= link_to "My Profile", myprofile_path %></li> -->
            <% else %>
            <!--<li><%= link_to new_pin_path do %>
              <span class="glyphicon glyphicon-plus"></span> List Soemthing
            <% end %>
          </li>
            <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li> 
             -->
            <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/pages/home.html.erb
<div class="jumbotron center">
	<h1>KickTheList</h1>

	
	<% if user_signed_in? %>
          <%= link_to "discover", pins_path %>
     
     <% else %>
			<p>Create and explore a collection of the worlds awesome and interesting things to do.</p>
				<%= link_to "log in", new_user_session_path, class: "btn btn-default" %>
				<%= link_to "sign up", new_user_registration_path, class: "btn btn-primary" %>	
			</p>
	<% end %>
</div>

app/views/pins/discover.html.erb
<%= render 'pages/home' unless user_signed_in? %>


<% if user_signed_in? %>

<br><br><br><br>



    <div class="center">
        <font color="white"> <h3>Discover what others have listed</font></h3>
        <%= link_to "Listed", discover_path, class: "btn btn-default active" %>
        <%= link_to "Kicked", discoverkicked_path, class: "btn btn-primary" %> <p>
         <br>
    </div>
        
<div class="row">
  <div class="col-md-offset-4 col-md-4">
<div id="pins-center" class="left">

      <% @pins.each do |pin| %>
       <% unless pin.image? %>
        <div class="panel panel-primary"> <%# changed from box panel and added row class atop %>
          <div class="panel-body">
                <div class= "media">
                  <div class="media-left", style="width: 75px;",>
                    <strong><%=link_to (pin.user.name), pin.user if pin.user %></strong>
                    <%=link_to (image_tag pin.user.image.url(:medium)), pin.user, :"data-no-turbolink" => true if pin.user %> <br>
                  </div> 
                    <div class="media-body media-middle", style="padding-left: 15px; font-size: 17px;" align="center">
                      <%= link_to pin.description, pin, :"data-no-turbolink" => true unless pin.image?%>
                      <s><%= link_to pin.description, pin, :"data-no-turbolink" => true if pin.image?%></s>
                      <p>
                            <div class="pull-right">
                            <%= image_tag pin.image.url(:medium), style:"
                                  width: 30px;" if pin.image?%>
                          </div>
                      <!-- <% if pin.user == current_user%>
                      <div class="actions">
                        <%= link_to 'kick', edit_pin_path(pin)%> 
                      </div>
                    <% end %> -->
                    </div>
                </div>
          </div>
        </div>  
      <% end %>
      <% end %>
</div> 
</div>
</div>
<% else %>
<%end%>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>
</body>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76095527-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/pins/discoverkicked.html.erb
<%= render 'pages/home' unless user_signed_in? %>


<% if user_signed_in? %>

      <br><br><br><br>
    <div class="center">
        <font color="white"> <h3>Discover what others have kicked</h3></font>
        <%= link_to "Listed", discover_path, class: "btn btn-default" %>
        <%= link_to "Kicked", discoverkicked_path, class: "btn btn-primary active" %> <p>
         <br>
    </div>
        
  <div class="row">
    <div class="col-md-offset-4 col-md-4">
      <div id="pins" class="left">

        <% @pins.each do |pin| %>
          <% if pin.image? %>
            <div class="panel panel-primary">
              <div class="panel-body">
                <div class= "media">
                  <strong><font color="black"> </font> <%=link_to (pin.user.name), pin.user if pin.user %></strong> 
                  <div class="media-left", style="width: 75px;",>
                     <%=link_to (image_tag pin.user.image.url(:medium)), pin.user, :"data-no-turbolink" => true if pin.user %> <br>
                  </div> 
                          <div class="media-body media-middle", style="font-size: 17px; margin-left: 3%" align="center"> <s>
                            <%= link_to pin.description, pin, :"data-no-turbolink" => true %> </s>
                          </div>
                            <!-- <% if pin.user == current_user%>
                            <div class="actions">
                              <%= link_to 'kick', edit_pin_path(pin)%> 
                            </div> 

                          <%=link_to (image_tag pin.user.image.url(:medium)), pin.user if pin.user %> <br>
                                <strong><%= pin.user.name if pin.user %></strong>

                          <% end %> -->
                      
                    
                </div>
              </div>  
            </div> 
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
  
  
<% else %>
<%end%>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>
</body>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76095527-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/pins/index.html.erb
<%= render 'pages/home' unless user_signed_in? %>


<% if user_signed_in? %>

<br><br><br><br>
    <div class="center">
        <font color="white"> <h3>Discover what others have listed</font></h3>
        <%= link_to "Listed", discover_path, class: "btn btn-default active" %>
        <%= link_to "Kicked", discoverkicked_path, class: "btn btn-primary" %> <p>
         <br>
    </div>
        
<div class="row">
  <div class="col-md-offset-3 col-md-6">
<div id="pins-center" class="left">

      <% @pins.each do |pin| %>
        <div class="panel panel-primary"> <!-- changed from box panel and added row class atop -->
          <div class="panel-body">
                <div class= "media">
                  <div class="media-left", style="width: 75px;",>
                    <%=link_to (image_tag pin.user.image.url(:medium)), pin.user, :"data-no-turbolink" => true if pin.user %> <br>
                    <strong><%= pin.user.name if pin.user %></strong>
                  </div> 
                    <div class="media-body media-middle", style="padding-left: 15px; font-size: 17px">
                      <%= link_to pin.description, pin, :"data-no-turbolink" => true unless pin.image?%>
                      <s><%= link_to pin.description, pin, :"data-no-turbolink" => true if pin.image?%></s>
                      <p>
                            <div class="pull-right">
                            <%= image_tag pin.image.url(:medium), style:"
                                  width: 30px;" if pin.image?%>
                          </div>
                      <!-- <% if pin.user == current_user%>
                      <div class="actions">
                        <%= link_to 'kick', edit_pin_path(pin)%> 
                      </div>
                    <% end %> -->
                    </div>
                </div>
          </div>
        </div>  
      <% end %>
</div> 
</div>
</div>
<% else %>
<%end%>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>
</body>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76095527-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/pins/mylist.html.erb
<%= render 'pages/home' unless user_signed_in? %>


<% if current_user %>

<br><br><br>
  <div class="center">
    <font color="white"><h2>Hi, <%= current_user.name %></h2></font>
      </div> <br><br>     
         <div class="center">
            <%= image_tag current_user.image.url(:medium) %><p><br> 
                <font color="white"><h4> you have 
                  <%= current_user.pins.count %> items listed 
                </h4></font> <br>
            <%= link_to "Add to your list", new_pin_path, class: "btn btn-success" %> &nbsp;&nbsp;&nbsp;
            <!-- <%= link_to "Edit your profile", edit_user_registration_path, class: "btn btn-default" %> -->
            <br><br><p>
            <!-- <%= link_to "Log out", destroy_user_session_path, method: :delete %> --> 
        </div>
  </div>
        
<div class="row">
<div class="col-md-offset-2 col-md-8">
      <div id="pins-center" class="left">
                
        <% @pins.each do |pin| %>
          <div class="box panel panel-default">
            <div class="panel-body">
                <div class= "media">
                    <div class="media-left">
                        <%= image_tag pin.user.image.url(:medium) %> 
                        <strong><%= pin.user.name if pin.user %></strong> 
                    </div>
                         <div class="media-body media-middle", style="padding-left: 10px; font-size: 17px">
                            <%= link_to pin.description, pin, :"data-no-turbolink" => true %>
                            <!-- <% if pin.user == current_user%>
                              <div class="actions">
                                <%= link_to 'kick', edit_pin_path(pin)%> 
                              </div>
                            <% end %> -->
                          </div>
                </div>
            </div>
          </div>  
        <% end %>
      </div> 
</div> 
</div> 
<% else %>
<%end%>

<div class="center">
   <%= will_paginate @pins, renderer: BootstrapPagination::Rails %>
</div>

</body>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76095527-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/pins/myprofile.html.erb
<% if user_signed_in? %>
<br><br><br>
	<div class="center">
		<font color="white"><h2>Hi, <%= current_user.name %></h2></font>
			</div> <br><br>     
	    	 <div class="center">
		     		<%= image_tag current_user.image.url(:medium) %><p><br> 
		     				<font color="white"><h4> you have
		     					<%= current_user.pins.count %> items listed 
		     				</h4></font> <br>
		        <%= link_to "View Your List", mylist_path, class: "btn btn-success" %> &nbsp;&nbsp;&nbsp;
		     		<%= link_to "Discover", discover_path, class: "btn btn-primary" %> 
		     		<br><br><p>
		     		<%= link_to "Edit your profile", edit_user_registration_path %>
		     		<!-- <%= link_to "Log out", destroy_user_session_path, method: :delete %> -->
	   		</div>
	</div>
<% else %>
<%end%>
</body>



<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76095527-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/users/show.html.erb
<%= render 'pages/home' unless user_signed_in? %>

<% if @user == current_user %>
<br><br>
  <div class="center">
    
  </div> <br> 
      

          <div class ="center" >
            <table class="table table-bordered" style= "width: 250px;" align="center">
                  <tboady>
                    <tr>
                      
                      <td class="center" colspan="3">
                        <%= image_tag current_user.image.url(:medium) %><p>
                        <font color="black"><h2><%= current_user.name %></h2></font>
                                            <p>
                            <div class="center">
                              <%= link_to "edit profile", edit_user_registration_path %>
                            </div> 
                      </td>
                    </tr>
                    <tr>
                      <td class="center">
                        <font color="black"><h4> listed <br>
                          <div class="center">
                            <font color="black"><h2>
                            <%= current_user.pins.count %> </font>
                          </div>
                      </td> 
                      <td class="center">
                        <font color="black"><h4> kicked <br>
                          <div class="center">
                            <font color="black"><h2>
                            <%= current_user.pins.count(:image_file_name) %> </font>
                          </div>
                      </td>
                    </tr>
                    <tr>
                        <td class="center" colspan="3">
                          <div class="center">
                            <font color="white"><h4>
                          <%= link_to '+ Add to Your List', new_pin_path, class: "btn btn-success btn-md" %> <!--, style: "
                         padding-bottom: 0px;
                         padding-top: 0px;
                         margin-bottom: 10px;
                         " %> &nbsp;&nbsp; <p> -->
                        </div>
                      </td>
                    </tr>
                 </tbody>
                </table>
           </div>

    
        <div class="center">
          <div style="
            margin-left: auto;
            width: 50%;
            margin-right: auto;">
                <div class="fb-share-button" data-href="#{request.protocol}#{request.host_with_port}#{request.fullpath}" data-layout="button" data-mobile-iframe="true" style="bottom: 5px;"> 
                </div>   &nbsp;&nbsp;
                 <a class="twitter-share-button"
                href="https://twitter.com/intent/tweet?text=Just%20accepted%20the%20Kickthelist%20challenge.%20Check%20out%20my%20list:">
                Tweet</a>
          </div> 

          <!-- <div class="center">
            <%= link_to '+add more', new_pin_path, class: "btn btn-success"%>
          </div> <br> -->

 <!--
    <div class="center">
        <div style="
            margin-left: auto;
            width: 20%;
            margin-right: auto;">
              <table class="table"> 
                  <tboady>
                    <tr>
                      <!--<td><%= link_to '+add more', new_pin_path, class: "btn btn-success btn-sm", style: 'padding-bottom: 0px;
                         padding-top: 2px' %>
                      </td>
                      <td><div class="fb-share-button" data-href="#{request.protocol}#{request.host_with_port}#{request.fullpath}" data-layout="button" data-mobile-iframe="true"> </div>  
                      </td>
                      <td>
                        <a class="twitter-share-button"
                        href="https://twitter.com/intent/tweet?text=Just%20accepted%20the%20Kickthelist%20challenge:">
                        Tweet</a>
                      </td>
                    </tr>
                 </tbody>
                </table>
          </div>
      </div> -->

<br><br>
  <div class="row">
  <div class="col-md-offset-3 col-md-6">
      <div id="pins-center" class="left">
                
        <% @user.pins.each do |pin| %>
          <div class="box panel panel-primary">
            <div class="panel-body">
                <div class= "media">
                    <div class="media-left">
                        <%= image_tag pin.user.image.url(:medium) %> 
                        <strong><%= pin.user.name if pin.user %></strong>
                    </div>
                         <div class="media-body media-middle", style="padding-left: 10px; font-size: 17px" align="left">
                            <%= link_to pin.description, pin, :"data-no-turbolink" => true unless pin.image? %> <p>

                                  <div class="media-body media-middle", style="padding-left: 10px; font-size: 17px"> <s>
                                  <%= link_to pin.description, pin, :"data-no-turbolink" => true if pin.image? %> </s>
                                  </div>
                            <div class="pull-right">
                            <%= image_tag pin.image.url(:medium), style:"
                                  width: 20px;" if pin.image?%>
                          </div>
                            <!-- <% if pin.user == current_user%>
                              <div class="actions">
                                <%= link_to 'kick', edit_pin_path(pin)%> 
                              </div>
                            <% end %> -->
                          </div>
                </div>
            </div>
          </div>  
      <% end %>
      </div> 
</div> 
</div> 



<% else %>

 <br><br><br>

 <div class="center">
            <table class="table table-bordered" style= "width: 250px;" align="center">
                  <tboady>
                    <tr>
                      
                      <td class="center" colspan="3">
                        <%= image_tag @user.image.url(:medium) %> <p>
                        <font color="black"><h2><%= @user.name%> </h2></font>
                                            <p>
                            <div class="center">
                              <%= link_to "edit profile", edit_user_registration_path %>
                            </div> 
                      </td>
                    </tr>
                    <tr>
                      <td class="center">
                        <font color="black"><h4> listed <br>
                          <div class="center">
                            <font color="black"><h2>
                            <%= @user.pins.count %> </font>
                          </div>
                      </td> 
                      <td class="center">
                        <font color="black"><h4> kicked <br>
                          <div class="center">
                            <font color="black"><h2>
                            <%= @user.pins.count(:image_file_name) %> </font>
                          </div>
                      </td>
                    </tr>
                    
                     <% if user_signed_in? %>
        
                                            <% else %>
                      <tr>
                        <td class="center" colspan="3">
                          <div class="center">
                            <font color="white"><h4>
                                     
                                            <div class="center">
                                             <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-success btn-lg", style: "padding-right: 60px; padding-left: 60px" %>
                                        </div> 
                                      <%end%>
                        </div>
                      </td>
                    </tr>
                 </tbody>
                </table>
           </div>
        </div>

   <div class="center">
          <div style="
            margin-left: auto;
            width: 50%;
            margin-right: auto;">
                <div class="fb-share-button" data-href="#{request.protocol}#{request.host_with_port}#{request.fullpath}" data-layout="button" data-mobile-iframe="true" style="bottom: 5px;"> 
                </div>   &nbsp;&nbsp;
                 <a class="twitter-share-button"
                href="https://twitter.com/intent/tweet?text=Just%20accepted%20the%20Kickthelist%20challenge.%20Check%20out%20my%20list:">
                Tweet</a>
          </div> 


<!--
    	<div class="center">
    		<font color="white"><h2> Welcome to <%= @user.name%>'s list</h2></font>
    			</div> <br>    
    	    	 <div class="center">
                <font color="white">
                  <h4><%= @user.name%> has listed <strong><%= @user.pins.count %></strong> things <br><br>
     		     		<%= image_tag @user.image.url(:medium) %> <br><br> 
    	   		</div> <br>

            <div class="center">
          <div style="
            margin-left: auto;
            width: 20%;
            margin-right: auto;">
              <table class="table"> 
                  <tboady>
                      <tr>
                       <td><%= link_to '+add more', new_pin_path, class: "btn btn-success btn-sm", style: 'padding-bottom: 0px;
                         padding-top: 2px' %>
                      </td>
                      <td><div class="fb-share-button" data-href="#{request.protocol}#{request.host_with_port}#{request.fullpath}" data-layout="button" data-mobile-iframe="true"> </div>  
                      </td>
                      <td>
                        <a class="twitter-share-button"
                        href="https://twitter.com/intent/tweet?text=Just%20accepted%20the%20Kickthelist%20challenge:">
                        Tweet</a>
                      </td>
                    </tr>
                 </tbody>
                </table>
          </div>
        </div> -->
        <br>
    	</div>

      <br>

    <div class="row">
  <div class="col-md-offset-3 col-md-6">
      <div id="pins-center" class="left">
                  
          <% @user.pins.each do |pin| %>
            <div class="box panel panel-primary">
            <div class="panel-body">
                <div class= "media">
                    <div class="media-left">
                        <%= image_tag pin.user.image.url(:medium) if pin.user %>
                        <strong><%= pin.user.name if pin.user %></strong>
                      </div> 
                        <div class="media-body media-middle", style="padding-left: 15px; font-size: 17px" align="left">
                            <%= link_to pin.description, pin, :"data-no-turbolink" => true unless pin.image? %> <p>

                                  <div class="media-body media-middle", style="padding-left: 15px; font-size: 17px"> <s>
                                  <%= link_to pin.description, pin, :"data-no-turbolink" => true if pin.image? %> </s>
                                  </div>
                          <p>
                            <div class="pull-right">
                            <%= image_tag pin.image.url(:medium), style:"
                                  width: 20px;" if pin.image?%>
                          </div>
                          <!-- <% if pin.user == current_user%>
                          <div class="actions">
                            <%= link_to 'kick', edit_pin_path(pin)%> 
                          </div>
                        <% end %> -->
                        </div>
                    </div>
              </div>
            </div>  
          <% end %>
        </div> 
    </div> 
    </div> 
<br>

<%end%>
</body>


<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-76095527-1', 'auto');
  ga('send', 'pageview');

</script>